{{- if gt .Values.portal.replicas 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "harbor.portal" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  minAvailable: 1
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: portal
{{- end }}