{{- if (gt (int .Values.core.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "harbor.core" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  minAvailable: 1
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: core
{{- end }}