{{- if (gt (int .Values.registry.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "harbor.registry" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  minAvailable: 1
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: registry
{{- end }}